---
- name: Install ruby-build
  homebrew:
    name: ruby-build
    # name: ruby_build@{{ ruby_build_version }}

- name: Install Ruby
  shell: >
    RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl)" ruby-build "{{ ruby_version }}" /usr/local
